backend: gloo
world_size: 8
master_addr: localhost
master_port: '12345'
dataset_cls_name: CIFAR10
data_aug_train:
    ToTensorTransform: {}
    FlipTransform: {p: 0.5}
    PaddingTransform: {pad_size: 4, pad_type: zero}
    RandomCropTransform: {crop_size: 32}
data_aug_test:
    ToTensorTransform: {}
architecture_spec: 'c3,16,3,1,1 r3 r3 r3 ap8,1,0 fc64,10'
preact: False
use_proj: False
dropout_prob: 0.0
max_steps: 64000
batch_size: 128
optimizer_cls_name: SGD
optimizer_args:
    lr: 0.1
    momentum: 0.9
    dampening: 0.0
    nesterov: False
    weight_decay: 0.0001
scheduler_cls_name: MultiStepLR
scheduler_step_unit: batch
scheduler_args:
    milestones: [32000, 48000]
    gamma: 0.1
checkpoint_strategy_cls_name: FrequencyCheckpointStrategy
checkpoint_strategy_args:
    unit: epoch
    frequency: 1
