backend: gloo
world_size: 8
master_addr: localhost
master_port: '12345'
dataset_cls_name: CIFAR10
data_aug:
    ToTensorTransform: {}
    ZeroMeanWhiteningTransform: {}
    FlipTransform: {p: 0.5}
    PaddingTransform: {pad_size: 0, pad_type: zero}
    RandomCropTransform: {crop_size: 32}
architecture_spec: 'c7,2,1,3,64 n a mp3,2,1 r3 r4 r6 r3 ap7,1,0 f512,1000'
preact: False
use_proj: False
dropout_prob: 0.0
max_steps: 10000
batch_size: 64
optimizer_cls_name: SGD
optimizer_args:
    lr: 0.1
    momentum: 0.9
    dampening: 0.0
    nesterov: False
    weight_decay: 0.0001
scheduler_cls_name: ReduceLROnPlateau
scheduler_args:
    mode: min
    factor: 0.1
    patience: 10
scheduler_step_unit: epoch
checkpoint_strategy_cls_name: FrequencyCheckpointStrategy
checkpoint_strategy_args:
    unit: epoch
    frequency: 6